# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avtomat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False, verbose_name='\u0412\u0440\u0435\u043c\u044f')),
                ('time_in_message', models.CharField(max_length=12, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0432 \u0441\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0438')),
                ('how_money', models.FloatField(verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0438\u043d\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u0438')),
                ('avtomat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtomat.Avtomat', verbose_name='\u0410\u0432\u0442\u043e\u043c\u0430\u0442')),
            ],
            options={
                'ordering': ('-time',),
                'db_table': 'collection',
                'verbose_name': '\u0418\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u0418\u043d\u043a\u0430\u0441\u0441\u0430\u0446\u0438\u0438',
            },
        ),
    ]
