# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-29 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043c\u0430\u0440\u0448\u0440\u0443\u0442\u0430')),
                ('car_number', models.CharField(max_length=15, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u044f')),
                ('driver', models.CharField(max_length=50, verbose_name='\u0412\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ('route_number',),
                'db_table': 'route',
                'verbose_name': '\u041c\u0430\u0440\u0448\u0440\u0443\u0442',
                'verbose_name_plural': '\u041c\u0430\u0440\u0448\u0440\u0443\u0442\u044b',
            },
        ),
    ]
